sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - /bin/sh -c "/bin/bash prepare_project.sh"
  - docker-compose build
  - docker-compose up -d
  - sleep 5

script:
  - docker-compose run system /bin/sh -c "cd /opt/app/culturaaccesible-system; touch travis.ci; bundle install; bundle exec rake prepare; bundle exec rake test"
  - sleep 1
  - /bin/sh -c "cd ./culturaaccesible-app; bundle install; rspec"
  - sleep 1

after_script:
  - docker-compose down

#notifications:
#  slack:
#    template:
#      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
#    rooms:
#      - devscola:l7PXPT2ycwSwtbwNI8Bd1hEb#fc_travis
