sudo: required
dist: trusty
group: edge 

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

services:
  - docker

before_install:
  - rvm install ruby-2.4.0
  - rvm use 2.4.0
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - /bin/sh -c "/bin/bash prepare_project.sh"
  - docker-compose -f docker-compose.travis.yml build
  - sleep 1
  - docker-compose -f docker-compose.travis.yml up -d
  - sleep 5

script:
  - docker-compose -f docker-compose.travis.yml run system /bin/sh -c "cd /opt/app/culturaaccesible-system; touch travis.ci; bundle install --jobs 3; gem install bundle; bundle exec rake test" -d
  - sleep 1
  - cd test-app
  - ls -la
  - touch travis.ci
  - gem install bundle
  - bundle --version
  - bundle install --path vendor --jobs 3
  - rake test
  - sleep 1

after_script:
  - docker-compose down

#notifications:
#  slack:
#    template:
#      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
#    rooms:
#      - devscola:l7PXPT2ycwSwtbwNI8Bd1hEb#fc_travis
