version: '2'
services:
  ionic:
    container_name: ionic-cuac-container
    image: devscola/culturaaccesible-ionic:latest
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/opt/app
      - bundle:/usr/local/bundle
    links:
      - selenium
      - mongo
    command: bash -c "/bin/bash use_project.sh"

  sinatra:
    container_name: sinatra-cuac-container
    image: devscola/culturaaccesible-sinatra:latest
    ports:
      - "4567:4567"
    volumes:
      - ./culturaaccesible-system:/opt/app/culturaaccesible-system
      - bundle:/usr/local/bundle
    links:
      - mongo
      - selenium
    command: bash -c "sh ensure_vendorization.sh"

  app:
    container_name: app-cuac-container
    build:
      context: culturaaccesible-app
      dockerfile: Dockerfile
    volumes:
      - ./culturaaccesible-app:/opt/app/culturaaccesible-app
      - bundle:/usr/local/bundle
    links:
      - ionic
      - selenium
      - mongo

  system:
    container_name: system-cuac-container
    build: 
      context: culturaaccesible-system
      dockerfile: Dockerfile.system
    volumes:
      - ./culturaaccesible-system:/opt/app/culturaaccesible-system
      - bundle:/usr/local/bundle
    links:
      - sinatra
      - mongo
      - selenium

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo-cuac-container
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
