version: '2'
services:
  app:
    container_name: app-cuac
    build:
      context: culturaaccesible-app
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/opt/app
    links:
      - system
    command: bash -c "/bin/bash prepare_project.sh"

  system:
    container_name: system
    build: 
      context: culturaaccesible-system
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
     - ./culturaaccesible-system:/opt/app/culturaaccesible-system
     - bundle:/usr/local/bundle
    links:
      - mongocontainer
      - selenium
    command: bash -c "bundle install --jobs 3 && bundle exec rake prepare && bundle exec rake"

  selenium:
    container_name: selenium-cuac
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongocontainer:
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
