version: '2'
services:
  app:
    container_name: app-cuac-container
    build:
      context: culturaaccesible-app
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/opt/app
    links:
      - selenium
      - mongo
    command: bash -c "/bin/bash use_project.sh"

  system:
    container_name: system-cuac-container
    build: 
      context: culturaaccesible-system
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
     - ./culturaaccesible-system:/opt/app/culturaaccesible-system
     - bundle:/usr/local/bundle
    links:
      - mongo
      - selenium
    command: bash -c "bundle install --jobs 3 && bundle exec rake prepare && bundle exec rake"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo-cuac-container
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
