version: '2'
services:
  ionicbuild:
    container_name: ionicbuild-cuac-container
    build:
      context: test-app
      dockerfile: Dockerfile.build
    ports:
      - "8100:8100"
    volumes:
     - ./test-app:/opt/app/test-app
     - bundle:/usr/local/bundle
    links:
      - sinatra
      - selenium
    command: bash -c "cd /opt/app/test-app; sh prepare_environment_tests.sh"

  sinatra:
    container_name: sinatra-cuac-container
    image: devscola/culturaaccesible-sinatra:latest
    ports:
      - "4567:4567"
    volumes:
      - ./culturaaccesible-system:/opt/app/culturaaccesible-system
      - bundle:/usr/local/bundle
    links:
      - mongo
      - selenium
    command: bash -c "cd /opt/app/culturaaccesible-system; sh prepare_environment_tests.sh"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo-cuac-container
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
