version: '2'
services:
  ionic:
    container_name: ionic-cuac-container
    image: devscola/culturaaccesible-ionic:latest
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/opt/app
      - ./culturaaccesible-app:/opt/app/culturaaccesible-app
      - bundle:/usr/local/bundle
    links:
      - system
      - selenium
      - mongo
    command: bash -c "sh use_project.sh"

  system:
    container_name: sinatra-cuac-container
    build:
      context: culturaaccesible-system
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - ./culturaaccesible-system:/opt/app/culturaaccesible-system
      - bundle:/usr/local/bundle
    links:
      - selenium
      - mongo
    command: bash -c "cd /opt/app/culturaaccesible-system; sh prepare_environment_tests.sh"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo-cuac-container
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
