version: '2'
services:
  ionicbuild:
    container_name: ionicbuild-cuac-container
    build:
      context: .
      dockerfile: Dockerfile.build
    ports:
      - "8100:8100"
    volumes:
     - .:/opt/app/test-app
     - bundle:/usr/local/bundle

    links:
      - selenium
    command: bash -c "sh prepare_environment_tests.sh"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

volumes:
  bundle:
    driver: local
