require_relative 'environment_configuration'
require 'rspec/core/rake_task'

SINATRA_PORT = retrieve_port
TRAVIS = retrieve_travis

def copy_build_in_local_mode
  if (TRAVIS == false)
    sh 'cp ../culturaaccesible-app/www ./. -r'
  end
end

task :default => :start

task :start do
  if (TRAVIS == false)
    sh "rerun --background -- rackup --port #{SINATRA_PORT} -o 0.0.0.0"
  end
  if (TRAVIS == true)
    sh "rerun --background -- rackup --port #{SINATRA_PORT} -o 0.0.0.0 &"
    sh "sleep 1"
    sh 'rspec spec/bdd'
  end
end

task :bdd do
  copy_build_in_local_mode
  sh 'rspec spec'
end

task :test => [:bdd] do
end

task :tag, [:tag] do |t, arg|
  copy_build_in_local_mode
  sh "rspec --tag #{arg.tag}"
end

desc 'Run labeled tests'
RSpec::Core::RakeTask.new do |test, args|
  test.pattern = Dir['spec/**/*_spec.rb']
  test.rspec_opts = args.extras.map { |tag| "--tag #{tag}" }
end
